INSERT INTO employees (first_name, last_name, email, phone_number, id_card_number, position_id)
VALUES
('Karolina', 'Szymański', 'karolina.szymański@example.com', '123456789', '1000', NULL),
('Dominika', 'Woźniak', 'dominika.woźniak@example.com', '123456780', '1001', NULL),
('Julia', 'Pawłowski', 'julia.pawłowski@example.com', '123456781', '1002', NULL),
('Mateusz', 'Nowak', 'mateusz.nowak@example.com', '123456782', '1003', NULL),
('Mateusz', 'Pawłowski', 'mateusz.pawłowski@example.com', '123456783', '1004', NULL),
('Wiktoria', 'Kozłowski', 'wiktoria.kozłowski@example.com', '123456784', '1005', NULL),
('Amelia', 'Zieliński', 'amelia.zieliński@example.com', '123456785', '1006', NULL),
('Wiktor', 'Zieliński', 'wiktor.zieliński@example.com', '123456786', '1007', NULL),
('Emilia', 'Lewandowski', 'emilia.lewandowski@example.com', '123456787', '1008', NULL),
('Kornelia', 'Kamiński', 'kornelia.kamiński@example.com', '123456788', '1009', NULL),
('Aleksandra', 'Michalski', 'aleksandra.michalski@example.com', '123456789', '1010', NULL),
('Daria', 'Mazur', 'daria.mazur@example.com', '123456780', '1011', NULL),
('Rafał', 'Mazur', 'rafał.mazur@example.com', '123456781', '1012', NULL),
('Grzegorz', 'Zając', 'grzegorz.zając@example.com', '123456782', '1013', NULL),
('Joanna', 'Kamiński', 'joanna.kamiński@example.com', '123456783', '1014', NULL),
('Piotr', 'Woźniak', 'piotr.woźniak@example.com', '123456784', '1015', NULL),
('Dominik', 'Piotrowski', 'dominik.piotrowski@example.com', '123456785', '1016', NULL),
('Maksymilian', 'Malinowski', 'maksymilian.malinowski@example.com', '123456786', '1017', NULL),
('Antoni', 'Zając', 'antoni.zając@example.com', '123456787', '1018', NULL),
('Maksymilian', 'Krawczyk', 'maksymilian.krawczyk@example.com', '123456788', '1019', NULL),
('Julia', 'Kowalski', 'julia.kowalski@example.com', '123456789', '1020', NULL),
('Kinga', 'Zając', 'kinga.zając@example.com', '123456780', '1021', NULL),
('Zuzanna', 'Jankowski', 'zuzanna.jankowski@example.com', '123456781', '1022', NULL),
('Wojciech', 'Grabowski', 'wojciech.grabowski@example.com', '123456782', '1023', NULL),
('Aleksandra', 'Szymański', 'aleksandra.szymański@example.com', '123456783', '1024', NULL),
('Martyna', 'Piotrowski', 'martyna.piotrowski@example.com', '123456784', '1025', NULL),
('Paweł', 'Grabowski', 'paweł.grabowski@example.com', '123456785', '1026', NULL),
('Anastasiia', 'Pawłowski', 'anastasiia.pawłowski@example.com', '123456786', '1027', NULL),
('Oskar', 'Zieliński', 'oskar.zieliński@example.com', '123456787', '1028', NULL),
('Grzegorz', 'Grabowski', 'grzegorz.grabowski@example.com', '123456788', '1029', NULL),
('Milena', 'Kamiński', 'milena.kamiński@example.com', '123456789', '1030', NULL),
('Katarzyna', 'Kozłowski', 'katarzyna.kozłowski@example.com', '123456780', '1031', NULL),
('Jakub', 'Jankowski', 'jakub.jankowski@example.com', '123456781', '1032', NULL),
('Magdalena', 'Kamiński', 'magdalena.kamiński@example.com', '123456782', '1033', NULL),
('Mikhail', 'Kowalski', 'mikhail.kowalski@example.com', '123456783', '1034', NULL),
('Natalia', 'Lewandowski', 'natalia.lewandowski@example.com', '123456784', '1035', NULL),
('Oleksii', 'Kozłowski', 'oleksii.kozłowski@example.com', '123456785', '1036', NULL),
('Michał', 'Wiśniewski', 'michał.wiśniewski@example.com', '123456786', '1037', NULL),
('Maksymilian', 'Kowalski', 'maksymilian.kowalski@example.com', '123456787', '1038', NULL),
('Olivier', 'Mazur', 'olivier.mazur@example.com', '123456788', '1039', NULL),
('Pola', 'Król', 'pola.król@example.com', '123456789', '1040', NULL),
('Maciej', 'Nowak', 'maciej.nowak@example.com', '123456780', '1041', NULL),
('Szymon', 'Krawczyk', 'szymon.krawczyk@example.com', '123456781', '1042', NULL),
('Diana', 'Kozłowski', 'diana.kozłowski@example.com', '123456782', '1043', NULL),
('Julia', 'Zieliński', 'julia.zieliński@example.com', '123456783', '1044', NULL),
('Illia', 'Michalski', 'illia.michalski@example.com', '123456784', '1045', NULL),
('Andżelika', 'Piotrowski', 'andżelika.piotrowski@example.com', '123456785', '1046', NULL),
('Maciej', 'Wiśniewski', 'maciej.wiśniewski@example.com', '123456786', '1047', NULL),
('Remigiusz', 'Kozłowski', 'remigiusz.kozłowski@example.com', '123456787', '1048', NULL),
('Mateusz', 'Lewandowski', 'mateusz.lewandowski@example.com', '123456788', '1049', NULL),
('Hanna', 'Dąbrowski', 'hanna.dąbrowski@example.com', '123456789', '1050', NULL),
('Filip', 'Kowalski', 'filip.kowalski@example.com', '123456780', '1051', NULL),
('Julia', 'Szymański', 'julia.szymański@example.com', '123456781', '1052', NULL),
('Bartosz', 'Krawczyk', 'bartosz.krawczyk@example.com', '123456782', '1053', NULL),
('Konrad', 'Kozłowski', 'konrad.kozłowski@example.com', '123456783', '1054', NULL),
('Oliwia', 'Piotrowski', 'oliwia.piotrowski@example.com', '123456784', '1055', NULL),
('Anhelina', 'Zając', 'anhelina.zając@example.com', '123456785', '1056', NULL),
('Natalia', 'Grabowski', 'natalia.grabowski@example.com', '123456786', '1057', NULL),
('Jakub', 'Wójcik', 'jakub.wójcik@example.com', '123456787', '1058', NULL),
('Nikola', 'Grabowski', 'nikola.grabowski@example.com', '123456788', '1059', NULL),
('Wiaczesław', 'Dąbrowski', 'wiaczesław.dąbrowski@example.com', '123456789', '1060', NULL),
('Hanna', 'Król', 'hanna.król@example.com', '123456780', '1061', NULL),
('Sandra', 'Lewandowski', 'sandra.lewandowski@example.com', '123456781', '1062', NULL),
('Oliwia', 'Dąbrowski', 'oliwia.dąbrowski@example.com', '123456782', '1063', NULL),
('Alessandro', 'Dąbrowski', 'alessandro.dąbrowski@example.com', '123456783', '1064', NULL),
('Julia', 'Michalski', 'julia.michalski@example.com', '123456784', '1065', NULL),
('Emil', 'Wójcik', 'emil.wójcik@example.com', '123456785', '1066', NULL),
('Dominika', 'Szczurowska', 'dominika.szczurowska@example.com', '123456786', '1067', NULL),
('Hubert', 'Michalski', 'hubert.michalski@example.com', '123456787', '1068', NULL),
('Ivan', 'Król', 'ivan.król@example.com', '123456788', '1069', NULL),
('Vanessa', 'Krawczyk', 'vanessa.krawczyk@example.com', '123456789', '1070', NULL),
('Julia', 'Gawrona', 'julia.gawrona@example.com', '123456780', '1071', NULL),
('Wiktor', 'Pawłowski', 'wiktor.pawłowski@example.com', '123456781', '1072', NULL),
('Emil', 'Woźniak', 'emil.woźniak@example.com', '123456782', '1073', NULL),
('Zuzanna', 'Kamiński', 'zuzanna.kamiński@example.com', '123456783', '1074', NULL),
('Aleksandra', 'Mazur', 'aleksandra.mazur@example.com', '123456784', '1075', NULL),
('Nina', 'Lewandowski', 'nina.lewandowski@example.com', '123456785', '1076', NULL),
('Walentyna', 'Pawłowski', 'walentyna.pawłowski@example.com', '123456786', '1077', NULL),
('Konrad', 'Michalski', 'konrad.michalski@example.com', '123456787', '1078', NULL),
('Filip', 'Piotrowski', 'filip.piotrowski@example.com', '123456788', '1079', NULL),
('Jakub', 'Grabowski', 'jakub.grabowski@example.com', '123456789', '1080', NULL),
('Mikołaj', 'Wójcik', 'mikołaj.wójcik@example.com', '123456780', '1081', NULL),
('Mateusz', 'Mazur', 'mateusz.mazur@example.com', '123456781', '1082', NULL),
('Oliwia', 'Lewandowski', 'oliwia.lewandowski@example.com', '123456782', '1083', NULL),
('Agata', 'Kowalski', 'agata.kowalski@example.com', '123456783', '1084', NULL),
('Szymon', 'Kozłowski', 'szymon.kozłowski@example.com', '123456784', '1085', NULL),
('Weronika', 'Jankowski', 'weronika.jankowski@example.com', '123456785', '1086', NULL),
('Igor', 'Król', 'igor.król@example.com', '123456786', '1087', NULL),
('Kacper', 'Nowak', 'kacper.nowak@example.com', '123456787', '1088', NULL),
('Oliwia', 'Krawczyk', 'oliwia.krawczyk@example.com', '123456788', '1089', NULL),
('Kinga', 'Krawczyk', 'kinga.krawczyk@example.com', '123456789', '1090', NULL),
('Maja', 'Piotrowski', 'maja.piotrowski@example.com', '123456780', '1091', NULL),
('Mateusz', 'Wójcik', 'mateusz.wójcik@example.com', '123456781', '1092', NULL),
('Nikola', 'Wiśniewski', 'nikola.wiśniewski@example.com', '123456782', '1093', NULL),
('Wiktoria', 'Kamiński', 'wiktoria.kamiński@example.com', '123456783', '1094', NULL),
('Adam', 'Król', 'adam.król@example.com', '123456784', '1095', NULL),
('Kacper', 'Zając', 'kacper.zając@example.com', '123456785', '1096', NULL),
('Mateusz', 'Zając', 'mateusz.zając@example.com', '123456786', '1097', NULL),
('Anna', 'Nowak', 'anna.nowak@example.com', '123456787', '1098', NULL),
('Damian', 'Dąbrowski', 'damian.dąbrowski@example.com', '123456788', '1099', NULL),
('Maksymilian', 'Dąbrowski', 'maksymilian.dąbrowski@example.com', '123456789', '1100', NULL),
('Alexander', 'Kowalski', 'alexander.kowalski@example.com', '123456780', '1101', NULL),
('Kuba', 'Zając', 'kuba.zając@example.com', '123456781', '1102', NULL),
('Vladyslav', 'Kamiński', 'vladyslav.kamiński@example.com', '123456782', '1103', NULL),
('Izabela', 'Dąbrowski', 'izabela.dąbrowski@example.com', '123456783', NULL, NULL),
('Anton', 'Wiśniewski', 'anton.wiśniewski@example.com', '123456784', NULL, NULL),
('Jakub', 'Pawłowski', 'jakub.pawłowski@example.com', '123456785', NULL, NULL),
('Mikołaj', 'Szymański', 'mikołaj.szymański@example.com', '123456786', NULL, NULL),
('Filip', 'Jankowski', 'filip.jankowski@example.com', '123456787', NULL, NULL),
('Ksawery', 'Nowak', 'ksawery.nowak@example.com', '123456788', NULL, NULL),
('Martyna', 'Woźniak', 'martyna.woźniak@example.com', '123456789', NULL, NULL),
('Filip', 'Byczkowski', 'filip.byczkowski@example.com', '123456780', NULL, NULL),
('Aleksandra', 'Lazur', 'aleksandra.lazur@example.com', '123456781', NULL, NULL),
('Marta', 'Szymański', 'marta.szymański@example.com', '123456782', NULL, NULL),
('Paulina', 'Wiśniewski', 'paulina.wiśniewski@example.com', '123456783', NULL, NULL),
('Wiktoria', 'Pawłowski', 'wiktoria.pawłowski@example.com', '123456784', NULL, NULL),
('Anna', 'Zieliński', 'anna.zieliński@example.com', '123456785', NULL, NULL),
('Konrad', 'Król', 'konrad.król@example.com', '123456786', NULL, NULL),
('Sara', 'Krawczyk', 'sara.krawczyk@example.com', '123456787', NULL, NULL),
('Zuzanna', 'Michalski', 'zuzanna.michalski@example.com', '123456788', NULL, NULL),
('Dawid', 'Jankowski', 'dawid.jankowski@example.com', '123456780', NULL, NULL),
('Mateusz', 'Kowalski', 'mateusz.kowalski@example.com', '123456781', NULL, NULL),
('Sofiia', 'Wójcik', 'sofiia.wójcik@example.com', '123456782', NULL, NULL),
('Michelle', 'Mazur', 'michelle.mazur@example.com', '123456783', NULL, NULL),
('Sara', 'Król', 'sara.król@example.com', '123456784', NULL, NULL),
('Magdalena', 'Jankowski', 'magdalena.jankowski@example.com', '123456785', NULL, NULL),
('Natalia', 'Woźniak', 'natalia.woźniak@example.com', '123456786', NULL, NULL);




--this bellow should be latest or the same

/*
-- Query: SELECT * FROM employee
-- Date: 2025-01-20 14:58
*/
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (1,'Karolina','Szymański','karolina.szymański@example.com','123456789','1000',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (2,'Dominika','Woźniak','dominika.woźniak@example.com','123456780','1001',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (3,'Julia','Pawłowski','julia.pawłowski@example.com','123456781','1002',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (4,'Mateusz','Nowak','mateusz.nowak@example.com','123456782','1003',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (5,'Mateusz','Pawłowski','mateusz.pawłowski@example.com','123456783','1004',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (6,'Wiktoria','Kozłowski','wiktoria.kozłowski@example.com','123456784','1005',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (7,'Amelia','Zieliński','amelia.zieliński@example.com','123456785','1006',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (8,'Wiktor','Zieliński','wiktor.zieliński@example.com','123456786','1007',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (9,'Emilia','Lewandowski','emilia.lewandowski@example.com','123456787','1008',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (10,'Kornelia','Kamiński','kornelia.kamiński@example.com','123456788','1009',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (11,'Aleksandra','Michalski','aleksandra.michalski@example.com','123456789','1010',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (12,'Daria','Mazur','daria.mazur@example.com','123456780','1011',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (13,'Rafał','Mazur','rafał.mazur@example.com','123456781','1012',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (14,'Grzegorz','Zając','grzegorz.zając@example.com','123456782','1013',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (15,'Joanna','Kamiński','joanna.kamiński@example.com','123456783','1014',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (16,'Piotr','Woźniak','piotr.woźniak@example.com','123456784','1015',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (17,'Dominik','Piotrowski','dominik.piotrowski@example.com','123456785','1016',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (18,'Maksymilian','Malinowski','maksymilian.malinowski@example.com','123456786','1017',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (19,'Antoni','Zając','antoni.zając@example.com','123456787','1018',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (20,'Maksymilian','Krawczyk','maksymilian.krawczyk@example.com','123456788','1019',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (21,'Julia','Kowalski','julia.kowalski@example.com','123456789','1020',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (22,'Kinga','Zając','kinga.zając@example.com','123456780','1021',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (23,'Zuzanna','Jankowski','zuzanna.jankowski@example.com','123456781','1022',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (24,'Wojciech','Grabowski','wojciech.grabowski@example.com','123456782','1023',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (25,'Aleksandra','Szymański','aleksandra.szymański@example.com','123456783','1024',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (26,'Martyna','Piotrowski','martyna.piotrowski@example.com','123456784','1025',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (27,'Paweł','Grabowski','paweł.grabowski@example.com','123456785','1026',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (28,'Anastasiia','Pawłowski','anastasiia.pawłowski@example.com','123456786','1027',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (29,'Oskar','Zieliński','oskar.zieliński@example.com','123456787','1028',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (30,'Grzegorz','Grabowski','grzegorz.grabowski@example.com','123456788','1029',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (31,'Milena','Kamiński','milena.kamiński@example.com','123456789','1030',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (32,'Katarzyna','Kozłowski','katarzyna.kozłowski@example.com','123456780','1031',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (33,'Jakub','Jankowski','jakub.jankowski@example.com','123456781','1032',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (34,'Magdalena','Kamiński','magdalena.kamiński@example.com','123456782','1033',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (35,'Mikhail','Kowalski','mikhail.kowalski@example.com','123456783','1034',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (36,'Natalia','Lewandowski','natalia.lewandowski@example.com','123456784','1035',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (37,'Oleksii','Kozłowski','oleksii.kozłowski@example.com','123456785','1036',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (38,'Michał','Wiśniewski','michał.wiśniewski@example.com','123456786','1037',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (39,'Maksymilian','Kowalski','maksymilian.kowalski@example.com','123456787','1038',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (40,'Olivier','Mazur','olivier.mazur@example.com','123456788','1039',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (41,'Pola','Król','pola.król@example.com','123456789','1040',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (42,'Maciej','Nowak','maciej.nowak@example.com','123456780','1041',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (43,'Szymon','Krawczyk','szymon.krawczyk@example.com','123456781','1042',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (44,'Diana','Kozłowski','diana.kozłowski@example.com','123456782','1043',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (45,'Julia','Zieliński','julia.zieliński@example.com','123456783','1044',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (46,'Illia','Michalski','illia.michalski@example.com','123456784','1045',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (47,'Andżelika','Piotrowski','andżelika.piotrowski@example.com','123456785','1046',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (48,'Maciej','Wiśniewski','maciej.wiśniewski@example.com','123456786','1047',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (49,'Remigiusz','Kozłowski','remigiusz.kozłowski@example.com','123456787','1048',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (50,'Mateusz','Lewandowski','mateusz.lewandowski@example.com','123456788','1049',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (51,'Hanna','Dąbrowski','hanna.dąbrowski@example.com','123456789','1050',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (52,'Filip','Kowalski','filip.kowalski@example.com','123456780','1051',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (53,'Julia','Szymański','julia.szymański@example.com','123456781','1052',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (54,'Bartosz','Krawczyk','bartosz.krawczyk@example.com','123456782','1053',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (55,'Konrad','Kozłowski','konrad.kozłowski@example.com','123456783','1054',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (56,'Oliwia','Piotrowski','oliwia.piotrowski@example.com','123456784','1055',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (57,'Anhelina','Zając','anhelina.zając@example.com','123456785','1056',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (58,'Natalia','Grabowski','natalia.grabowski@example.com','123456786','1057',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (59,'Jakub','Wójcik','jakub.wójcik@example.com','123456787','1058',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (60,'Nikola','Grabowski','nikola.grabowski@example.com','123456788','1059',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (61,'Wiaczesław','Dąbrowski','wiaczesław.dąbrowski@example.com','123456789','1060',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (62,'Hanna','Król','hanna.król@example.com','123456780','1061',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (63,'Sandra','Lewandowski','sandra.lewandowski@example.com','123456781','1062',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (64,'Oliwia','Dąbrowski','oliwia.dąbrowski@example.com','123456782','1063',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (65,'Alessandro','Dąbrowski','alessandro.dąbrowski@example.com','123456783','1064',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (66,'Julia','Michalski','julia.michalski@example.com','123456784','1065',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (67,'Emil','Wójcik','emil.wójcik@example.com','123456785','1066',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (68,'Dominika','Szczurowska','dominika.szczurowska@example.com','123456786','1067',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (69,'Hubert','Michalski','hubert.michalski@example.com','123456787','1068',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (70,'Ivan','Król','ivan.król@example.com','123456788','1069',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (71,'Vanessa','Krawczyk','vanessa.krawczyk@example.com','123456789','1070',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (72,'Julia','Gawrona','julia.gawrona@example.com','123456780','1071',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (73,'Wiktor','Pawłowski','wiktor.pawłowski@example.com','123456781','1072',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (74,'Emil','Woźniak','emil.woźniak@example.com','123456782','1073',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (75,'Zuzanna','Kamiński','zuzanna.kamiński@example.com','123456783','1074',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (76,'Aleksandra','Mazur','aleksandra.mazur@example.com','123456784','1075',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (77,'Nina','Lewandowski','nina.lewandowski@example.com','123456785','1076',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (78,'Walentyna','Pawłowski','walentyna.pawłowski@example.com','123456786','1077',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (79,'Konrad','Michalski','konrad.michalski@example.com','123456787','1078',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (80,'Filip','Piotrowski','filip.piotrowski@example.com','123456788','1079',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (81,'Jakub','Grabowski','jakub.grabowski@example.com','123456789','1080',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (82,'Mikołaj','Wójcik','mikołaj.wójcik@example.com','123456780','1081',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (83,'Mateusz','Mazur','mateusz.mazur@example.com','123456781','1082',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (84,'Oliwia','Lewandowski','oliwia.lewandowski@example.com','123456782','1083',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (85,'Agata','Kowalski','agata.kowalski@example.com','123456783','1084',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (86,'Szymon','Kozłowski','szymon.kozłowski@example.com','123456784','1085',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (87,'Weronika','Jankowski','weronika.jankowski@example.com','123456785','1086',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (88,'Igor','Król','igor.król@example.com','123456786','1087',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (89,'Kacper','Nowak','kacper.nowak@example.com','123456787','1088',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (90,'Oliwia','Krawczyk','oliwia.krawczyk@example.com','123456788','1089',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (91,'Kinga','Krawczyk','kinga.krawczyk@example.com','123456789','1090',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (92,'Maja','Piotrowski','maja.piotrowski@example.com','123456780','1091',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (93,'Mateusz','Wójcik','mateusz.wójcik@example.com','123456781','1092',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (94,'Nikola','Wiśniewski','nikola.wiśniewski@example.com','123456782','1093',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (95,'Wiktoria','Kamiński','wiktoria.kamiński@example.com','123456783','1094',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (96,'Adam','Król','adam.król@example.com','123456784','1095',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (97,'Kacper','Zając','kacper.zając@example.com','123456785','1096',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (98,'Mateusz','Zając','mateusz.zając@example.com','123456786','1097',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (99,'Anna','Nowak','anna.nowak@example.com','123456787','1098',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (100,'Damian','Dąbrowski','damian.dąbrowski@example.com','123456788','1099',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (101,'Maksymilian','Dąbrowski','maksymilian.dąbrowski@example.com','123456789','1100',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (102,'Alexander','Kowalski','alexander.kowalski@example.com','123456780','1101',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (103,'Kuba','Zając','kuba.zając@example.com','123456781','1102',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (104,'Vladyslav','Kamiński','vladyslav.kamiński@example.com','123456782','1103',NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (105,'Izabela','Dąbrowski','izabela.dąbrowski@example.com','123456783',NULL,NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (106,'Anton','Wiśniewski','anton.wiśniewski@example.com','123456784',NULL,NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (107,'Jakub','Pawłowski','jakub.pawłowski@example.com','123456785',NULL,NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (108,'Mikołaj','Szymański','mikołaj.szymański@example.com','123456786',NULL,NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (109,'Filip','Jankowski','filip.jankowski@example.com','123456787',NULL,NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (110,'Ksawery','Nowak','ksawery.nowak@example.com','123456788',NULL,NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (111,'Martyna','Woźniak','martyna.woźniak@example.com','123456789',NULL,NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (112,'Filip','Byczkowski','filip.byczkowski@example.com','123456780',NULL,NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (113,'Aleksandra','Lazur','aleksandra.lazur@example.com','123456781',NULL,NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (114,'Marta','Szymański','marta.szymański@example.com','123456782',NULL,NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (115,'Paulina','Wiśniewski','paulina.wiśniewski@example.com','123456783',NULL,NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (116,'Wiktoria','Pawłowski','wiktoria.pawłowski@example.com','123456784',NULL,NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (117,'Anna','Zieliński','anna.zieliński@example.com','123456785',NULL,NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (118,'Konrad','Król','konrad.król@example.com','123456786',NULL,NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (119,'Sara','Krawczyk','sara.krawczyk@example.com','123456787',NULL,NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (120,'Zuzanna','Michalski','zuzanna.michalski@example.com','123456788',NULL,NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (121,'Dawid','Jankowski','dawid.jankowski@example.com','123456780',NULL,NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (122,'Mateusz','Kowalski','mateusz.kowalski@example.com','123456781',NULL,NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (123,'Sofiia','Wójcik','sofiia.wójcik@example.com','123456782',NULL,NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (124,'Michelle','Mazur','michelle.mazur@example.com','123456783',NULL,NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (125,'Sara','Król','sara.król@example.com','123456784',NULL,NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (126,'Magdalena','Jankowski','magdalena.jankowski@example.com','123456785',NULL,NULL);
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone_number`,`id_card_number`,`position_id`) VALUES (127,'Natalia','Woźniak','natalia.woźniak@example.com','123456786',NULL,NULL);
